import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Goodword",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
    // 웨일 브라우저 아이콘을 숨기는 스크립트 (가장 빠른 실행을 위해 head에 삽입)
    const whaleFixScript = `
      (function() {
        const HIDER_ID = 'whale-quick-search-container';

        const hideIcon = (node) => {
          if (!node) return;
          try {
            if (node.shadowRoot) {
              const style = document.createElement('style');
              style.textContent = ':host { display: none !important; }';
              node.shadowRoot.appendChild(style);
            } else {
              node.style.setProperty('display', 'none', 'important');
            }
          } catch (e) {}
        };

        const observer = new MutationObserver((mutations) => {
          for (const mutation of mutations) {
            for (const node of mutation.addedNodes) {
              if (node.nodeType === 1 && node.id === HIDER_ID) {
                hideIcon(node);
              }
            }
          }
        });

        observer.observe(document.documentElement, { childList: true, subtree: true });
      })();
    `;

    return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: whaleFixScript }} />
        <meta name="whale-quick-search" content="disabled" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* "새글 등록" 버튼을 화면 우측 상단에 고정 */}
        <div className="fixed top-4 right-4 z-50">
          <Link href="/create" className="bg-blue-400 text-white font-semibold px-5 py-2 rounded-full shadow-lg hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-all duration-300 ease-in-out">
            새글 등록
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
